Test for macos-14 runner (8) : change for test debug(3)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -150,6 +150,7 @@ jobs:
           for s3fs_brew_pkg in ${S3FS_BREW_PACKAGES}; do
             if brew list | grep -q ${s3fs_brew_pkg}; then if brew outdated | grep -q ${s3fs_brew_pkg}; then HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade ${s3fs_brew_pkg}; fi; else HOMEBREW_NO_AUTO_UPDATE=1 brew install ${s3fs_brew_pkg}; fi
           done
+          find / -name libstdbuf.so 2>/dev/null || echo "some error"
 
       - name: Install awscli2
         run: |
